export const criteriaData = [
  [
    { left: 'Project Size', right: 'Project Complexity' },
    { left: 'Project Size', right: 'Project Importance' },
    { left: 'Project Size', right: 'Development Approach' },
    { left: 'Project Complexity', right: 'Project Importance' },
    { left: 'Project Complexity', right: 'Development Approach' },
    { left: 'Project Importance', right: 'Development Approach' },
  ],
  [
    { left: 'Plan Risk Management', right: 'Identify Risks' },
    { left: 'Plan Risk Management', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Plan Risk Responses' },
    { left: 'Plan Risk Management', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Management', right: 'Monitor Risks' },
    { left: 'Identify Risks', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Plan Risk Responses' },
    { left: 'Identify Risks', right: 'Implement Risk Responses' },
    { left: 'Identify Risks', right: 'Monitor Risks' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Plan Risk Responses', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Responses', right: 'Monitor Risks' },
    { left: 'Implement Risk Responses', right: 'Monitor Risks' },
  ],
  [
    { left: 'Plan Risk Management', right: 'Identify Risks' },
    { left: 'Plan Risk Management', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Plan Risk Responses' },
    { left: 'Plan Risk Management', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Management', right: 'Monitor Risks' },
    { left: 'Identify Risks', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Plan Risk Responses' },
    { left: 'Identify Risks', right: 'Implement Risk Responses' },
    { left: 'Identify Risks', right: 'Monitor Risks' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Plan Risk Responses', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Responses', right: 'Monitor Risks' },
    { left: 'Implement Risk Responses', right: 'Monitor Risks' },
  ],
  [
    { left: 'Plan Risk Management', right: 'Identify Risks' },
    { left: 'Plan Risk Management', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Plan Risk Responses' },
    { left: 'Plan Risk Management', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Management', right: 'Monitor Risks' },
    { left: 'Identify Risks', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Plan Risk Responses' },
    { left: 'Identify Risks', right: 'Implement Risk Responses' },
    { left: 'Identify Risks', right: 'Monitor Risks' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Plan Risk Responses', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Responses', right: 'Monitor Risks' },
    { left: 'Implement Risk Responses', right: 'Monitor Risks' },
  ],
  [
    { left: 'Plan Risk Management', right: 'Identify Risks' },
    { left: 'Plan Risk Management', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Plan Risk Management', right: 'Plan Risk Responses' },
    { left: 'Plan Risk Management', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Management', right: 'Monitor Risks' },
    { left: 'Identify Risks', right: 'Perform Qualitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Identify Risks', right: 'Plan Risk Responses' },
    { left: 'Identify Risks', right: 'Implement Risk Responses' },
    { left: 'Identify Risks', right: 'Monitor Risks' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Perform Quantitative Risk Analysis' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Qualitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Plan Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Implement Risk Responses' },
    { left: 'Perform Quantitative Risk Analysis', right: 'Monitor Risks' },
    { left: 'Plan Risk Responses', right: 'Implement Risk Responses' },
    { left: 'Plan Risk Responses', right: 'Monitor Risks' },
    { left: 'Implement Risk Responses', right: 'Monitor Risks' },
  ],
]